apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: 24036-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: nginx
          image: akhilmanne/akhil-webapp-24036:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: webapp-storage
          envFrom:
            - configMapRef:
                name: webapp-config
            - secretRef:
                name: webapp-secret
      volumes:
        - name: webapp-storage
          persistentVolumeClaim:
            claimName: webapp-pvc
