apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
  namespace: 24036-ns
type: Opaque
data:
  username: dXNlci0yNDAzNg==         # user-24036
  password: TXlTZWNyZXRLZXkxMjM=    # MySecretKey123
  